force-app/main/default/objects/Finance_Account__c/Finance_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Savings</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Investment</fullName>
            </value>
            <value>
                <fullName>Wallet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{000000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS__c/fields/Amount_Value__c.field-meta.xml
<CustomField>
    <fullName>Amount_Value__c</fullName>
    <label>Amount Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS__c/fields/Balance_Update__c.field-meta.xml
<CustomField>
    <fullName>Balance_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Balance Update?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SMS__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SMS__c/fields/Finance_Account__c.field-meta.xml
<CustomField>
    <fullName>Finance_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Account</label>
    <referenceTo>Finance_Account__c</referenceTo>
    <relationshipLabel>SMS Messages</relationshipLabel>
    <relationshipName>SMS_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS__c/fields/From_Account__c.field-meta.xml
<CustomField>
    <fullName>From_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Account</label>
    <referenceTo>Finance_Account__c</referenceTo>
    <relationshipLabel>SMS (From Account)</relationshipLabel>
    <relationshipName>SMS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS__c/fields/SA_Available_Balance__c.field-meta.xml
<CustomField>
    <fullName>SA_Available_Balance__c</fullName>
    <label>SA Available Balance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WalletControllerAmazonPay.cls
public with sharing class WalletControllerAmazonPay {
    
    public static final String CLASS_NAME = 'WalletControllerAmazonPay';
    
    public WalletControllerAmazonPay() {

    }

    public static SMS__c processForAmazonWallet(SMS__c inputSMS){
        SMS__c sms = inputSMS.clone(false, true); // Util.cloneTransactionPE(inputSMS); 
        return sms;
    }

    // public static SMS__c processForOthers(SMS__c sms, Map<String, Finance_Account__c> allBankAccountsMap){
        
    //     if(sms.content__c.toUpperCase().contains('AMAZON PAY')){
    //         sms.type__c = 'balance_update';
    //         sms.Balance_Update__c = true;
    //         sms.From_Account__c = allBankAccountsMap.get('AMAZON-WA').Id;
            
    //         if(sms.content__c.contains('added to Amazon Pay balance')){
    //             sms.SA_Available_Balance__c = sms.content__c.split(' ')[9];
    //             sms.amount_value__c = sms.content__c.split(' ')[1];
    //         }
    //         else if(sms.content__c.contains('added to Amazon Pay Wallet')){
    //             sms.SA_Available_Balance__c = sms.content__c.split(' ')[9];
    //             sms.amount_value__c = sms.content__c.split(' ')[1];
    //         }
    //         else if(sms.content__c.contains('Refund')){
    //             sms.SA_Available_Balance__c = sms.content__c.split(' ')[18];
    //             sms.amount_value__c = sms.content__c.split(' ')[7];
    //         }
    //     }

    //     // Copy of above, to be mde for Vodafone / Jio account
    //     // if(sms.content__c.toUpperCase().contains('AMAZON PAY')){
    //     //     sms.type__c = 'balance_update';
    //     //     sms.Balance_Update__c = true;
    //     //     sms.Finance__Account__c = allBankAccountsMap.get('AMAZON-WA').Id;
            
    //     //     if(sms.content__c.contains('added to Amazon Pay balance')){
    //     //         sms.SA_Available_Balance__c = sms.content__c.split(' ')[9];
    //     //         sms.amount_value__c = sms.content__c.split(' ')[1];
    //     //     }
    //     //     else if(sms.content__c.contains('added to Amazon Pay Wallet')){
    //     //         sms.SA_Available_Balance__c = sms.content__c.split(' ')[9];
    //     //         sms.amount_value__c = sms.content__c.split(' ')[1];
    //     //     }
    //     //     else if(sms.content__c.contains('Refund')){
    //     //         sms.SA_Available_Balance__c = sms.content__c.split(' ')[18];
    //     //         sms.amount_value__c = sms.content__c.split(' ')[7];
    //     //     }
    //     // }

    //     if((sms.amount_value__c != null) && (sms.amount_value__c.endsWith('.'))){
    //         sms.amount_value__c = sms.amount_value__c.substring(0, sms.amount_value__c.length() - 1);
    //     }
    //     if((sms.SA_Available_Balance__c != null) && sms.SA_Available_Balance__c.endsWith('.')){
    //         sms.SA_Available_Balance__c = sms.SA_Available_Balance__c.substring(0, sms.SA_Available_Balance__c.length() - 1);
    //     }

    //     return sms;
    // }
}