force-app/main/default/objects/Finance_Account__c/Finance_Account__c.object-meta.xml
<CustomObject>
    <label>Finance Account</label>
    <nameField>
        <label>Finance Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{000000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS__c/fields/Finance_Account__c.field-meta.xml
<CustomField>
    <fullName>Finance_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Account</label>
    <referenceTo>Finance_Account__c</referenceTo>
    <relationshipLabel>SMS Messages</relationshipLabel>
    <relationshipName>SMS_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QueueablePopulateFinanceAccount.cls
public without sharing class QueueablePopulateFinanceAccount implements Queueable, Database.AllowsCallouts {

    public static final String CLASS_NAME = 'QueueablePopulateFinanceAccount';
    
    private List<SMS__c> smsRecords;

    public QueueablePopulateFinanceAccount(List<SMS__c> smsRecords) {
        this.smsRecords = smsRecords;
    }

    public void execute(QueueableContext context) {
        try {
            System.debug('Before populateFinanceAccountFromSMS: ' + smsRecords);

            // Populate the Finance Account Id
            Map<String, Finance_Account__c> mapAccounts = Util.getAllAccounts();
            smsRecords = Util.populateFinanceAccountFromSMS(smsRecords, mapAccounts);
            System.debug('After populateFinanceAccountFromSMS: ' + smsRecords);

            // Upsert the enriched SMS__c records into the database
            upsert smsRecords External_Id__c;
        } 
        catch (Exception e) {
            System.debug('Error in QueueablePopulateFinanceAccount: ' + e.getStackTraceString());
            FinPlanLogger.logError(CLASS_NAME, 'execute', e, null); // the last parameter is the entity Id, which is not available outside the loop
        }
        finally{
            // Chain the next Queueable
            System.enqueueJob(new QueueableExtractBeneficiaryAndAmount(smsRecords));
        }
    }
}