force-app/main/default/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{000000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QueueablePopulateProcessedInfo.cls
public without sharing class QueueablePopulateProcessedInfo implements Queueable, Database.AllowsCallouts {

    public static final String CLASS_NAME = 'QueueablePopulateProcessedInfo';
    
    private List<SMS__c> smsRecords;

    public QueueablePopulateProcessedInfo(List<SMS__c> smsRecords) {
        this.smsRecords = smsRecords;
    }

    public void execute(QueueableContext context) {
        try {
            System.debug('Before populateProcessedInfo: ' + smsRecords);

            // Populate Processed Info
            smsRecords = Util.populateProcessedInfo(smsRecords);
            System.debug('After populateProcessedInfo: ' + smsRecords);

            // Upsert the enriched SMS__c records into the database
            upsert smsRecords External_Id__c;

            System.debug('SMS records successfully enriched and upserted.');
        } 
        catch (Exception e) {
            System.debug('Error in QueueablePopulateProcessedInfo: ' + e.getStackTraceString());
            FinPlanLogger.logError(CLASS_NAME, 'extractBalanceInfo', e, null); // the last parameter is the entity Id, which is not available outside the loop
        }
    }
}