force-app/main/default/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <displayFormat>SMS-{000000}</displayFormat>
        <label>SMS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed</fullName>
                <default>true</default>
                <label>Not Processed</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvocableSMSHandler.cls
public with sharing class InvocableSMSHandler {
    /**
     * Invocable method to call the enrichData method.
     */
    @InvocableMethod(label='Enrich the data' description='Enrich the data')
    public static List<SMS__c> enrichData(List<SMS__c> smsList) {   
        List<SMS__c> data = SMSHandler.enrichData(smsList);
        for(SMS__c sms : data){
            sms.status__c = 'Processed';
        }
        return data;
    }
}